server:
  port: 8081
  #servlet:
    #context-path: /chess-user

spring:
  application:
    name: chess-user
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 4c7b6a1eabe5d3e50a52c534c56ecd3f6b1ca861
    url: jdbc:mysql://chessn_keephighwe:4c7b6a1eabe5d3e50a52c534c56ecd3f6b1ca861@nnsf9.h.filess.io:3307/chessn_keephighwe
    username: chessn_keephighwe
    hikari:
      maximum-pool-size: 5  # Max pool size
      minimum-idle: 1        # Minimum idle connections
      idle-timeout: 10000    # Idle timeout
      connection-timeout: 10000  # Connection timeout
      max-lifetime: 30000   # Max lifetime of connections
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      zone: default
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chess-game
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
