server:
  port: 8081
  #servlet:
    #context-path: /chess-user

spring:
  application:
    name: chess-user
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: myuser
    password: MyPass123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 10000
      max-lifetime: 30000
      connection-test-query: SELECT 1 FROM dual
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      zone: default
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chess-game
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"